CREATE TABLE IF NOT EXISTS `zeekota_houserobbery_players` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `identifier` VARCHAR(96) NOT NULL,
    `framework` VARCHAR(24) NOT NULL DEFAULT 'auto',
    `display_name` VARCHAR(96) NOT NULL DEFAULT 'Unknown',
    `houses_broken_into` INT UNSIGNED NOT NULL DEFAULT 0,
    `successful_robberies` INT UNSIGNED NOT NULL DEFAULT 0,
    `failed_robberies` INT UNSIGNED NOT NULL DEFAULT 0,
    `cancelled_robberies` INT UNSIGNED NOT NULL DEFAULT 0,
    `total_loot_value` INT UNSIGNED NOT NULL DEFAULT 0,
    `best_robbery_value` INT UNSIGNED NOT NULL DEFAULT 0,
    `total_xp` INT UNSIGNED NOT NULL DEFAULT 0,
    `current_level` INT UNSIGNED NOT NULL DEFAULT 1,
    `failed_keypad_attempts` INT UNSIGNED NOT NULL DEFAULT 0,
    `armed_peds_killed` INT UNSIGNED NOT NULL DEFAULT 0,
    `times_police_alerted` INT UNSIGNED NOT NULL DEFAULT 0,
    `current_streak` INT UNSIGNED NOT NULL DEFAULT 0,
    `highest_streak` INT UNSIGNED NOT NULL DEFAULT 0,
    `last_robbery_at` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
    `updated_at` INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_zeekota_houserobbery_identifier` (`identifier`),
    KEY `idx_zeekota_houserobbery_level` (`current_level`),
    KEY `idx_zeekota_houserobbery_xp` (`total_xp`),
    KEY `idx_zeekota_houserobbery_success` (`successful_robberies`),
    KEY `idx_zeekota_houserobbery_loot` (`total_loot_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `zeekota_houserobbery_logs` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `identifier` VARCHAR(96) NOT NULL,
    `action` VARCHAR(40) NOT NULL,
    `house_id` INT UNSIGNED DEFAULT NULL,
    `tier` INT UNSIGNED DEFAULT NULL,
    `loot_value` INT UNSIGNED NOT NULL DEFAULT 0,
    `xp` INT UNSIGNED NOT NULL DEFAULT 0,
    `metadata` LONGTEXT NULL,
    `created_at` INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_zeekota_houserobbery_logs_identifier` (`identifier`),
    KEY `idx_zeekota_houserobbery_logs_action` (`action`),
    KEY `idx_zeekota_houserobbery_logs_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
